# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth
  labels:
    app:  auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 3 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name:  auth
          image:  sergrking/auth:latest
          ports:
            - containerPort:  5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
